# Generated by Django 5.1.5 on 2025-04-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.TextField()),
                ('firstName', models.TextField()),
                ('streetNumber', models.IntegerField()),
                ('streetName', models.TextField()),
                ('aptNumber', models.IntegerField()),
                ('zipCode', models.IntegerField()),
                ('dob', models.CharField(max_length=10)),
                ('dor', models.CharField(max_length=10)),
                ('affiliation', models.CharField(max_length=2)),
                ('precinctNumber', models.IntegerField()),
                ('v20', models.BooleanField()),
                ('v21s', models.BooleanField()),
                ('v21p', models.BooleanField()),
                ('v22', models.BooleanField()),
                ('v23', models.BooleanField()),
                ('voterScore', models.IntegerField()),
            ],
        ),
    ]
