# Generated by Django 5.1.5 on 2025-04-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='aptNumber',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='precinctNumber',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='streetNumber',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voterScore',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='zipCode',
            field=models.TextField(),
        ),
    ]
