# Generated by Django 5.1.5 on 2025-04-05 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_alter_voter_aptnumber_alter_voter_precinctnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='v21s',
            new_name='v21t',
        ),
    ]
