# Generated by Django 5.1.5 on 2025-04-19 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_collaborator_invites', to='project.profile'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_collaborator_invites', to='project.profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='project.profile'),
        ),
        migrations.AlterField(
            model_name='eventcollaborator',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.profile'),
        ),
        migrations.AlterField(
            model_name='eventinvite',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_event_invites', to='project.profile'),
        ),
        migrations.AlterField(
            model_name='eventinvite',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_event_invites', to='project.profile'),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='post_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.profile'),
        ),
    ]
