# Generated by Django 5.1.5 on 2025-04-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_collaborator_invitee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
