# Generated by Django 5.1.5 on 2025-05-02 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_event_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='project.event'),
        ),
    ]
