# Generated by Django 5.1.5 on 2025-02-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImageURL',
            field=models.TextField(),
        ),
    ]
